This is C:\Program Files\MiKTeX 2.9\miktex\bin\x64\makeindex.exe, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file E:/DropBox Portable/Dropbox/BA/Dokumentation/Arbeit_2.0/bachelor.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file bachelor.acn....done (46 entries accepted, 0 rejected).
Sorting entries....done (294 comparisons).
Generating output file bachelor.acr....done (77 lines written, 0 warnings).
Output written in bachelor.acr.
Transcript written in bachelor.alg.
